name: Update Contributors

on:
  push:  # Triggers the workflow when there is a push to the repo
    branches:
      - main  # or any other branch you want to monitor
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Upgrade to v3

    - name: Set up Python
      uses: actions/setup-python@v3  # Upgrade to v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run update script
      run: |
        python scripts/update_contributors.py  # This runs your Python script

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add README.md
        git commit -m "Update contributor tiers"
        git push
