name: shelter_partner
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_functions: ^4.5.8
  http: ^1.1.0
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  csv: ^5.0.2
  uuid: ^4.2.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  fluttertoast: ^8.2.4
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  go_router: ^13.0.0
  email_validator: ^2.1.17
  cached_network_image: ^3.3.0
  firebase_storage: ^11.5.6
  image_picker: ^1.0.4
  webview_flutter: ^4.4.2
  webview_flutter_web: ^0.2.2+4
  url_launcher: ^6.2.2
  intl: ^0.18.1
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.14.0
  package_info_plus: ^4.2.0
  infinite_scroll_pagination: ^4.0.0
  cupertino_icons: ^1.0.6
  qonversion_flutter: ^9.1.5
  auto_size_text: ^3.0.0
  icon_decoration: ^2.1.0
  fl_chart: ^0.65.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  mockito: ^5.4.4
  fake_cloud_firestore: ^2.4.1+8
  firebase_auth_mocks: ^0.13.0
  
dependency_overrides:
  google_maps_flutter_web: ^0.5.6  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/csv/

  fonts:
    - family: CabinBold
      fonts:
        - asset: assets/fonts/CabinSketch-Bold.ttf
    - family: CabinRegular
      fonts:
        - asset: assets/fonts/CabinSketch-Regular.ttf
